"""add cancelledAt to events

Revision ID: da287f6521b3
Revises: 7a4f5ce7f1b2
Create Date: 2026-04-01 11:24:54.493952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da287f6521b3'
down_revision = '7a4f5ce7f1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelledAt', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('cancelledAt')

    # ### end Alembic commands ###