[mypy]
python_version = 3.12
ignore_missing_imports = True
follow_imports = silent
namespace_packages = True
explicit_package_bases = True
pretty = True
show_error_codes = True
exclude = (?x)(
    .*_pb2\.py$
    | .*_pb2_grpc\.py$
    | .*[\\/]migrations[\\/]versions[\\/].*
)
