[mypy]
python_version = 3.12
ignore_missing_imports = True
follow_imports = silent
namespace_packages = True
explicit_package_bases = True
pretty = True
show_error_codes = True
mypy_path = $MYPY_CONFIG_FILE_DIR
disable_error_code = import-untyped
exclude = (^|/)(?:.*_pb2(?:_grpc)?\.py|migrations/versions/.*)$

[mypy-models]
disable_error_code = name-defined

[mypy-migrations.*]
ignore_errors = True

[mypy-seat_inventory_pb2,seat_inventory_pb2_grpc]
follow_imports = skip
ignore_errors = True
