"""add_expiresAt_to_transfers

Revision ID: dd172ee7b2fd
Revises: c91b3a44d2f1
Create Date: 2026-04-02 12:37:38.756852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd172ee7b2fd'
down_revision = 'c91b3a44d2f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiresAt', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_column('expiresAt')

    # ### end Alembic commands ###