# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: seat_inventory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'seat_inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14seat_inventory.proto\x12\rseatinventory\"W\n\x0fHoldSeatRequest\x12\x14\n\x0cinventory_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x1d\n\x15hold_duration_seconds\x18\x03 \x01(\x05\"[\n\x10HoldSeatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x12\n\nheld_until\x18\x03 \x01(\t\x12\x12\n\nerror_code\x18\x04 \x01(\t\"*\n\x12ReleaseSeatRequest\x12\x14\n\x0cinventory_id\x18\x01 \x01(\t\"&\n\x13ReleaseSeatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\'\n\x0fSellSeatRequest\x12\x14\n\x0cinventory_id\x18\x01 \x01(\t\"#\n\x10SellSeatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\",\n\x14GetSeatStatusRequest\x12\x14\n\x0cinventory_id\x18\x01 \x01(\t\"Q\n\x15GetSeatStatusResponse\x12\x14\n\x0cinventory_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x12\n\nheld_until\x18\x03 \x01(\t2\xe2\x02\n\x14SeatInventoryService\x12K\n\x08HoldSeat\x12\x1e.seatinventory.HoldSeatRequest\x1a\x1f.seatinventory.HoldSeatResponse\x12T\n\x0bReleaseSeat\x12!.seatinventory.ReleaseSeatRequest\x1a\".seatinventory.ReleaseSeatResponse\x12K\n\x08SellSeat\x12\x1e.seatinventory.SellSeatRequest\x1a\x1f.seatinventory.SellSeatResponse\x12Z\n\rGetSeatStatus\x12#.seatinventory.GetSeatStatusRequest\x1a$.seatinventory.GetSeatStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'seat_inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HOLDSEATREQUEST']._serialized_start=39
  _globals['_HOLDSEATREQUEST']._serialized_end=126
  _globals['_HOLDSEATRESPONSE']._serialized_start=128
  _globals['_HOLDSEATRESPONSE']._serialized_end=219
  _globals['_RELEASESEATREQUEST']._serialized_start=221
  _globals['_RELEASESEATREQUEST']._serialized_end=263
  _globals['_RELEASESEATRESPONSE']._serialized_start=265
  _globals['_RELEASESEATRESPONSE']._serialized_end=303
  _globals['_SELLSEATREQUEST']._serialized_start=305
  _globals['_SELLSEATREQUEST']._serialized_end=344
  _globals['_SELLSEATRESPONSE']._serialized_start=346
  _globals['_SELLSEATRESPONSE']._serialized_end=381
  _globals['_GETSEATSTATUSREQUEST']._serialized_start=383
  _globals['_GETSEATSTATUSREQUEST']._serialized_end=427
  _globals['_GETSEATSTATUSRESPONSE']._serialized_start=429
  _globals['_GETSEATSTATUSRESPONSE']._serialized_end=510
  _globals['_SEATINVENTORYSERVICE']._serialized_start=513
  _globals['_SEATINVENTORYSERVICE']._serialized_end=867
# @@protoc_insertion_point(module_scope)
