# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import seat_inventory_pb2 as seat__inventory__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in seat_inventory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SeatInventoryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HoldSeat = channel.unary_unary(
                '/seatinventory.SeatInventoryService/HoldSeat',
                request_serializer=seat__inventory__pb2.HoldSeatRequest.SerializeToString,
                response_deserializer=seat__inventory__pb2.HoldSeatResponse.FromString,
                _registered_method=True)
        self.ReleaseSeat = channel.unary_unary(
                '/seatinventory.SeatInventoryService/ReleaseSeat',
                request_serializer=seat__inventory__pb2.ReleaseSeatRequest.SerializeToString,
                response_deserializer=seat__inventory__pb2.ReleaseSeatResponse.FromString,
                _registered_method=True)
        self.SellSeat = channel.unary_unary(
                '/seatinventory.SeatInventoryService/SellSeat',
                request_serializer=seat__inventory__pb2.SellSeatRequest.SerializeToString,
                response_deserializer=seat__inventory__pb2.SellSeatResponse.FromString,
                _registered_method=True)
        self.GetSeatStatus = channel.unary_unary(
                '/seatinventory.SeatInventoryService/GetSeatStatus',
                request_serializer=seat__inventory__pb2.GetSeatStatusRequest.SerializeToString,
                response_deserializer=seat__inventory__pb2.GetSeatStatusResponse.FromString,
                _registered_method=True)


class SeatInventoryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HoldSeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseSeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SellSeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeatStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SeatInventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HoldSeat': grpc.unary_unary_rpc_method_handler(
                    servicer.HoldSeat,
                    request_deserializer=seat__inventory__pb2.HoldSeatRequest.FromString,
                    response_serializer=seat__inventory__pb2.HoldSeatResponse.SerializeToString,
            ),
            'ReleaseSeat': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseSeat,
                    request_deserializer=seat__inventory__pb2.ReleaseSeatRequest.FromString,
                    response_serializer=seat__inventory__pb2.ReleaseSeatResponse.SerializeToString,
            ),
            'SellSeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SellSeat,
                    request_deserializer=seat__inventory__pb2.SellSeatRequest.FromString,
                    response_serializer=seat__inventory__pb2.SellSeatResponse.SerializeToString,
            ),
            'GetSeatStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeatStatus,
                    request_deserializer=seat__inventory__pb2.GetSeatStatusRequest.FromString,
                    response_serializer=seat__inventory__pb2.GetSeatStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'seatinventory.SeatInventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('seatinventory.SeatInventoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SeatInventoryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HoldSeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seatinventory.SeatInventoryService/HoldSeat',
            seat__inventory__pb2.HoldSeatRequest.SerializeToString,
            seat__inventory__pb2.HoldSeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseSeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seatinventory.SeatInventoryService/ReleaseSeat',
            seat__inventory__pb2.ReleaseSeatRequest.SerializeToString,
            seat__inventory__pb2.ReleaseSeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SellSeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seatinventory.SeatInventoryService/SellSeat',
            seat__inventory__pb2.SellSeatRequest.SerializeToString,
            seat__inventory__pb2.SellSeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSeatStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seatinventory.SeatInventoryService/GetSeatStatus',
            seat__inventory__pb2.GetSeatStatusRequest.SerializeToString,
            seat__inventory__pb2.GetSeatStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
