"""add_favorite_events

Revision ID: adb8ba176815
Revises: b83e6f752272
Create Date: 2026-04-03 04:33:08.421885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adb8ba176815'
down_revision = 'b83e6f752272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favoriteEvents', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=True, server_default='{}'))

    # Backfill nulls then tighten to NOT NULL
    op.execute("UPDATE users SET \"favoriteEvents\" = '{}' WHERE \"favoriteEvents\" IS NULL")
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('favoriteEvents', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('favoriteEvents')

    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
